apiVersion: v1
kind: Service
metadata:
  name: tunecloud-db-exporter-svc
  labels:
    app: tunecloud-db-exporter
spec:
  selector:
    app: tunecloud-db-exporter
  ports:
    - name: db-metrics
      port: 9187
      targetPort: 9187