apiVersion: v1
kind: Service
metadata:
  name: tunecloud-server-svc
  labels:
    app: tunecloud-server
spec:
  ports:
    - name: http-metrics
      port: 4000
      targetPort: 4000
  selector:
    app: tunecloud-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tunecloud-server-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: tunecloud-server
  endpoints:
    - port: http-metrics
      path: /metrics