apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunecloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunecloud-server
  template:
    metadata:
      labels:
        app: tunecloud-server
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: tunecloud-server
          image: ghcr.io/egorpirkov/tunecloud-server:sha-f5b36be
          env:
            - name: DATABASE_URL
              value: "postgresql://tunecloud:tunecloud@tunecloud-db:5432/tunecloud"
            - name: MUSIC_DIR
              value: "/music"
            - name: ADMIN_USERNAME
              value: egorpirkov
            - name: ADMIN_PASSWORD
              value: admin
          envFrom:
            - secretRef:
                name: spotify-secret
            - secretRef:
                name: jwt-secret
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: covers-storage
              mountPath: /app/covers
            - name: music-storage
              mountPath: /music
      volumes:
        - name: covers-storage
          persistentVolumeClaim:
            claimName: covers-pvc
        - name: music-storage
          hostPath:
            path: /home/pirkov/music
            type: Directory
