global:
  domain: tunecloud.local
  grafanaDomain: grafana.tunecloud.local
server:
  image: ghcr.io/egorpirkov/tunecloud-server:sha-26931da
  replicas: 1
client:
  image: ghcr.io/egorpirkov/tunecloud-client:sha-26931da
  replicas: 1
